### ISSUE TITLE
some css classes are not namespaced

### ISSUE THREAD

**Issue by xxvii** [nicolafranchini/VenoBox#133]
Hello,
some css classes are not namespaced (or without a namespaced parent) and can cause some conflicts when the same css classes are used outside venobox.

```css
.figlio{
    box-shadow: 0 0 12px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
    max-width: 100%;
    text-align: initial;
}

img.figlio{
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -o-user-select: none;
    user-select: none;
}

.animated{
    webkit-transition: margin 300ms ease-out;
    transition: margin 300ms ease-out;
}

.animate-in{
    opacity: 1;
}

.animate-out{
    opacity: 0;
}
```

I suggest to change the rules to:

```css
.vbox-content .figlio{
    box-shadow: 0 0 12px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
    max-width: 100%;
    text-align: initial;
}

.vbox-content img.figlio{
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -o-user-select: none;
    user-select: none;
}

.vbox-content.animated{
    webkit-transition: margin 300ms ease-out;
    transition: margin 300ms ease-out;
}

.vbox-content.animate-in{
    opacity: 1;
}

.vbox-content.animate-out{
    opacity: 0;
}
```
