### ISSUE TITLE
Prevent vertical scroll

### ISSUE THREAD

**Issue by sashabeep** [nicolafranchini/VenoBox#170]
Is there any parameter to fit media content to the screen vertically without scrolling?

**Comment by nunhes** [comment]
I need that too.

**Comment by mmjaeger** [comment]
so do I

**Comment by Joedmin** [comment]
I used the following CSS:
```css
.vbox-overlay {
	height: 100%;
}

.vbox-container {
	height: 100%;
	overflow: hidden !important;
}

.vbox-content {
	height: 100%;
}

.vbox-child {
	height: 100%;
	background-color: transparent !important;
}

	.vbox-child img {
		height: 100%;
		width: auto;
	}
```
