### ISSUE TITLE
Little problem on iPhone, picture not centered vertically

### ISSUE THREAD

**Issue by Le-future** [nicolafranchini/VenoBox#46]
Hi there!

FIrstly, thank you so much for your plugin, it does the job :-)

I've implemented the 1.5.3 version today and I note a little problem on iPhone, see the screenshot :<br>
<a href="http://imgur.com/EwccRzd.png"><img src="http://i.imgur.com/EwccRzd.png" title="source: imgur.com" /></a>

As you can see, the picture is not centered vertically compared to the arrows.

Any idea to solve this?

Best

**Comment by carlpeterson** [comment]
Hey, did you ever solve this issue? I'm having similar issues on my page, except in desktop.

**Comment by KasperAndersson** [comment]
@Le-future & @carlpeterson Try this, and remember to prefix the css..

```css
.vbox-content {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
```
